name: Prune Artifacts

# This is a script to remove all artifacts every month. By default it's 3 months, I think.
# This may be removed in the future when we don't have so many builds which could end up
# filling up the storage space

on:
  schedule:
    # Every day at 1am
    - cron: '0 1 * * *'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Prune artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        age: '4 weeks'
        skip-tags: true
