name: Tests - EVM

on:
  workflow_dispatch:
  pull_request:
    branches:
      - feature/evm
  push:
    branches:
      - feature/evm
    tags:
      - evm

env:
  NODE_URL: "http://127.0.0.1:19551/"

jobs:
  build-binaries:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo ./make.sh pkg-install-deps && sudo ./make.sh pkg-install-llvm

    - name: Build binaries
      run: TARGET="x86_64-pc-linux-gnu" ./make.sh build
      
    - name: Upload binaries
      uses: actions/upload-artifact@v3
      with:
        name: defibins
        path: |
          build/src/defid
          build/src/defi-cli
          scripts/fixtures.sh

  node-rpc-tests:
    runs-on: ubuntu-latest
    needs: build-binaries
    steps:
    - name: Download binaries
      uses: actions/download-artifact@v3
      with:
        name: defibins
        
    - name: Chores
      run: |
        chmod uog+x build/src/defid build/src/defi-cli scripts/fixtures.sh

    - name: Run defid node
      run: |
        ./build/src/defid -regtest -daemon -debug=rpc -printtoconsole -rpcallowip=0.0.0.0/0 -rpcbind=0.0.0.0 -masternode_operator=mswsMVsyGMj1FzDMbbxw2QW3KvQAv2FKiy -masternode_owner=mwsZw8nF7pKxWH8eoKL9tPxTpaFkz7QeLU -dummypos=0 -subsidytest=1 -txnotokens=0 -txindex=1 -amkheight=0 -bayfrontheight=1 -clarkequayheight=3 -dakotaheight=4 -dakotacrescentheight=5 -eunosheight=6 -eunospayaheight=7 -fortcanningheight=8 -fortcanningmuseumheight=9 -fortcanninghillheight=10 -fortcanningroadheight=11 -fortcanningcrunchheight=12 -fortcanningspringheight=13 -fortcanninggreatworldheight=14 -fortcanningepilogueheight=15 -grandcentralheight=16 -nextnetworkupgradeheight=17

    - name: Push fixtures
      run: |
        sleep 5
        ./scripts/fixtures.sh
      
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '^1.17.0'

    - name: Set up go eth test suites library
      uses: actions/checkout@v3
      with:
        repository: 'DeFiCh/go-ethlibs'

    - name: Run EVM RPC tests
      run: go test -v ./node/rpc_meta_test.go
