name: Tests - EVM

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint_cargo_fmt:
    name: Lint (cargo fmt)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af
        with:
          profile: minimal
          toolchain: nightly
          target: wasm32-unknown-unknown
          default: true
          override: true
          components: rustfmt, clippy

      - run: |
          cd src/rust
          cargo fmt --all -- --check
  
  lint_cargo_clippy:
    name: Lint (cargo clippy)
    runs-on: ubuntu-latest
    steps:
      - uses: arduino/setup-protoc@64c0c85d18e984422218383b81c52f8b077404d3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af
        with:
          profile: minimal
          toolchain: nightly
          target: wasm32-unknown-unknown
          default: true
          override: true
          components: rustfmt, clippy

      - run: |
          cd src/rust
          cargo clippy
  
  test_cargo:
    name: Test (cargo)
    runs-on: ubuntu-latest
    steps:
      - uses: arduino/setup-protoc@64c0c85d18e984422218383b81c52f8b077404d3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af
        with:
          profile: minimal
          toolchain: nightly
          target: wasm32-unknown-unknown
          default: true
          override: true
          components: rustfmt, clippy
          
      - run: |
          cd src/rust
          cargo test --no-fail-fast
